# Generated by Django 3.0.6 on 2020-05-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketDictionary', '0002_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='market',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='marketDictionary.Market'),
        ),
    ]
