# Generated by Django 3.0.6 on 2020-05-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketDictionary', '0003_ticker_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketDictionary.Market'),
        ),
    ]
