# Generated by Django 3.0.6 on 2020-05-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketDictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analysis', models.DateField()),
                ('header', models.TextField()),
                ('content', models.TextField()),
                ('paragraph_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyAnalysis.AnalysisType')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketDictionary.Ticker')),
            ],
        ),
    ]
