# Generated by Django 3.0.6 on 2020-05-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyAnalysis', '0004_auto_20200519_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
